export const CREATE_POST = 'CREATE_POST'
export const FETCH_BOOKS = 'FETCH_BOOKS'
export const REQUEST_BOOKS = 'REQUEST_BOOKS'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'